spring.application.name=legacybuilder

# Tell Spring Boot where the database is (Notice it points to the 5432 port and the umascryfall DB)
spring.datasource.url=jdbc:postgresql://localhost:5432/umascryfall
spring.datasource.username=postgres
spring.datasource.password=Rosepetal4

# Tell Hibernate to automatically create/update our SQL tables based on our Java classes!
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true